config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: "home#index", as: :user_root

  resources :relations, only: [:create, :destroy] do
    collection do
      get "refresh"
      post "refresh_list"
    end
  end

  get "@:id" => "users#show", as: :user

  resources :projects, path: :diy

  resources :publications, only: [:create, :destroy] do
    new do
      get ':type', action: :new, as: ""
    end
    collection do
      post "trix_attachment"
    end
    member do
      get '(/:index)', action: :show, as: ""
    end
  end

  devise_for :users, path:"account", controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :notifications do
    collection do
      post :clean
    end
  end

  resources :comments, only: [:destroy]
  resources :statuses, only: [:index, :show, :destroy] do
    resources :comments, only: [:new, :create]
  end

  ##
  # 管理
  authenticate :user, -> (user) { user.admin? } do
    scope :admin do
      resources :statistics, only: [:index]
      mount PgHero::Engine, at: "pghero"
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 会匹配所有剩下的 url，并 render error，它之后的 route 不会匹配
  # match '*path', to: 'home#error_404', via: :all

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :destroy]

  # 处理 status 的锚点跳转
  def show
    statusable = @status.statusable
    case statusable
    when Project
      redirect_to statusable
    when Relation
      case statusable.relationable
      ##
      # 如果这个 relation 是和一个 status 发生的关系，那么回跳两次：
      # 1. 下面跳到 status 处。
      # 2. 再次来到 show 里，得到 status 的 statusable 后再跳，比如是个 publication。
      # 有些递归的意思，停止条件是：statusable 不再是 status。
      #  举个例子：我 like 了一个 发布图片的 status，因此会产生一个 like status，同时这个
      #     like status 会生成一个 notification 通知图片的发布者，而发布者能够通过点击
      #     notification 里的 link 跳到具体的图片 status。
      #     当发生时，首先解析 like status 的 show，发现是个 relation 而且 relationable
      #     是个 status，其实就是那个图片 status，会直接跳转到 图片 status 的 show，再解析
      #     发现 statusable 是个 Publication，于是就跳到图片的 status 了。
      # （趁现在还能记清赶快记下，之后又要分析 :p）
      #
      when Project, User, Status
        redirect_to statusable.relationable
      when Publication, Comment
        redirect_to_content statusable.relationable
      end
    when Publication, Comment
      redirect_to_content statusable
    end
  end

  def index
    @statuses = Status.all
  end

  def destroy
    @status.destroy
    redirect_to :back
  end

  private

  def set_status
    @status = Status.find(params[:id])
    authorize @status
  end

  ##
  # Publication, Comment
  #
  def redirect_to_content(content)
    project = @status.project
    # 分辨出 comment 的锚点
    anchor = content.is_a?(Comment) ? "comment-#{content.id}" : "status-#{@status.id}"

    redirect_to project_path(project,
      page: project.page_of_status(@status),  # 算出在 status 在 project show 的第几页
      anchor: anchor)
  end

end

app/views/statuses/_comment_form.html.erb
<%= form_tag status_comments_path(status) do %>
  <div class="comment-form">
    <div class="input-group input-group-sm">
      <%= text_field_tag("comment[content]", "", class: "form-control") %>

      <span class="input-group-btn">
        <%= submit_tag("回应", class: "btn btn-secondary", disabled: "") %>
      </span>
    </div>
  </div>
<% end %>

app/views/statuses/_content.html.erb
<% if statusable.respond_to?(:content_type) %>
  <%= render "statuses/statusables/#{statusable.content_type.underscore}",
    contentable: statusable %>
<% else %>
  <%# TODO: relation 的 view %>
  <%= statusable.try(:name) %>
<% end %>

app/views/statuses/_status.html.erb
<% statusable = status.statusable %>
<% user = status.user %>
<% comments = status.comments %>

<% cache [status, statusable, user, cache_key_for_comments(comments), :relation_v1] do %>

  <% if statusable.present? %>
    <div class="status-item" id="status-<%= status.id %>" name="status-<%= status.id %>" data-action-type="<%= status.action_type %>">
      <div class="pull-left">
        <%= avatar_tag user, :normal %>
      </div>

      <div class="status-main">
        <div class="status-item-head">

          <% cache user do %>
            <%= link_to user.name, user %>
          <% end %>

          <span class="status-project-name">
            在 <%= link_to status.statusable_project.try(:name), project_path(status.statusable_project) %>
          </span>

          <span>
            <%= "#{status.action_name}了 " %>
            <%= link_to status.name, status, "data-turbolinks" => "false" %>
          </span>
        </div>

        <div class="status-item-body">
          <% cache statusable do %>
            <div class="content">
              <%= render "statuses/content", statusable: statusable %>
            </div>
          <% end %>

          <div class="actions">
            <span class="created_at">
              <%= timeago_tag status.created_at %>
            </span>

            <%# 这里是和 status 发生关系，这样便于从 notification 那里跳到这个status %>
            <%= relation_tag_for_cache status, :like %>

            <%= link_to "回应", new_status_comment_path(status), remote: true , class: "new-comment" %>
            <%= link_to "删除", status, method: :delete, class: "auth hidden",
                data: {confirm: t("confirm.delete"), "user-id" => "#{user.id}"  } %>

            <div class="comments">
              <%= render "comments/comments", comments: comments %>
              <div id="comment-form"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/statuses/_statusable.html.erb
<% if statusable.respond_to?(:content_type) %>
  <%= render "statuses/statusables/#{statusable.content_type.underscore}",
    publication: statusable %>
<% else %>
  <%# TODO: relation 的 view %>
  <%= statusable.try(:name) %>
<% end %>

app/views/statuses/index.html.erb
<h1>状态</h1>
<%= render @statuses %>


<% content_for "secondary-content" do %>
  <h2>推荐</h2>
<% end %>