config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: "home#index", as: :user_root

  resources :relations, only: [:create, :destroy] do
    collection do
      get "refresh"
      post "refresh_list"
    end
  end

  get "@:id" => "users#show", as: :user

  resources :projects, path: :diy

  resources :publications, only: [:create, :destroy] do
    new do
      get ':type', action: :new, as: ""
    end
    collection do
      post "trix_attachment"
    end
    member do
      get '(/:index)', action: :show, as: ""
    end
  end

  devise_for :users, path:"account", controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :notifications do
    collection do
      post :clean
    end
  end

  resources :comments, only: [:destroy]
  resources :statuses, only: [:index, :show, :destroy] do
    resources :comments, only: [:new, :create]
  end

  ##
  # 管理
  authenticate :user, -> (user) { user.admin? } do
    scope :admin do
      resources :statistics, only: [:index]
      mount PgHero::Engine, at: "pghero"
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 会匹配所有剩下的 url，并 render error，它之后的 route 不会匹配
  # match '*path', to: 'home#error_404', via: :all

end

app/models/notification.rb
##
# 通知类。
# 在 status 创建后自动创建，通知相关用户。
#
class Notification < ActiveRecord::Base

  # 为后面的 notification view 服务的，指明模板的名字，而不是操作的action
  enum notify_type: [:relationship, :publication, :comment, :project]

  belongs_to :actor, class_name: :User
  belongs_to :user
  # 通知都是由 status 触发的，比如：发的留言、关注的项目、发布的图片等
  belongs_to :status

  scope :unread, -> { where(read_at: nil) }

  class << self
    def read!(ids = [])
      return if ids.blank?
      Notification.where(id: ids).update_all(read_at: Time.now)
    end

    def unread_count(user)
      Notification.where(user: user).unread.count
    end
  end

  def read?
    self.read_at.present?
  end

  ##
  # 标题，谁 在 哪里 干 了 什么
  # publication：小王 在 趣人网 发布 了 图片
  # relation： 小王 喜欢了 你发布在 趣人网的 图片，小王关注了你
  # comment： 小王 评论了 你发布在 趣人网的 图片
  def title
    who = actor.name

    statusable = status.statusable
    case notify_type  # 根据 statusable 的类型定的
    when "relationship"
      do_what = status.action_name
      relationable = statusable.relationable

      case relationable
      when User
        to_what = relationable.name == user.name ? "你" : relationable.name
      when Project
        to_what = "你的 #{relationable.name}"
      when Status  # publication,包括 comment 的 status
        to_what = "你在 #{relationable.project.name} 的 #{relationable.statusable_name}"
      when Publication
        # Publication 还不能被发生关系，转移到了 status
      end

      "#{who} #{do_what}了 #{to_what}。"
    when "publication"
      at_where = statusable.project.name
      do_what = status.action_name
      to_what = statusable.name

      "#{who} 在你的 #{at_where} #{do_what}了 #{to_what}。"
    when "comment"
      to_what = "你在 #{statusable.project.name} 的 #{status.name}"
      "#{who} 评论了 #{to_what}"
    when "project"
      # 不用通知
    end

  end

  # TODO: 需要显示的内容
  def content

  end
end

app/controllers/notifications_controller.rb
##
# 提供通知
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications.includes(:actor).order('id desc')

    unread_ids = []
    @notifications.each do |n|
      unread_ids << n.id unless n.read?
    end
    Notification.read!(unread_ids)

    # 对于已经取出来的，其 read_at 还是不变的
    @notification_groups = @notifications.group_by { |note| note.created_at.to_date }
  end

  def clean
    Notification.where(user_id: current_user.id).delete_all
    redirect_to notifications_path
  end
end

app/views/notifications/_notification.html.erb
<div id="notification-<%= notification.id %>"
     data-id="<%= notification.id %>"
     class="media notification notification-<%= notification.notify_type %>
       <%= ' unread' if !notification.read? %>">
  <div class="media-left mr-2">
    <%= avatar_tag notification.actor, :small %>
  </div>

  <div class="media-body">
    <%= link_to notification.status, "data-turbolinks" => "false" do %>
      <div class="media-heading">
        <%= notification.title %>
      </div>
      <div class="media-content">
        <%= render "notifications/#{notification.notify_type}", notification: notification %>
      </div>
    <% end %>
  </div>

  <div class="media-right">
    <%= l notification.created_at, format: :short %>
  </div>
</div>

app/views/notifications/index.html.erb
<div class="notifications">
  <div class="heading clearfix">
    <h1>所有通知</h1>
    <span class="pull-right">
      <%= button_to "清空", clean_notifications_path, class: 'btn btn-sm btn-danger', method: 'clean' %>
    </span>
  </div>
  <div class="list">
    <% if @notifications.blank? %>
      <div class="no-records">没有通知</div>
    <% else %>
      <% @notification_groups.each do |group, notifications| %>
        <div class="notification-group">
          <div class="group-title"><%= fa_icon('clock-o') + " #{group}" %></div>
          <%= render notifications %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>