config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: "home#index", as: :user_root

  resources :relations, only: [:create, :destroy] do
    collection do
      get "refresh"
      post "refresh_list"
    end
  end

  get "@:id" => "users#show", as: :user

  resources :projects, path: :diy

  resources :publications, only: [:create, :destroy] do
    new do
      get ':type', action: :new, as: ""
    end
    collection do
      post "trix_attachment"
    end
    member do
      get '(/:index)', action: :show, as: ""
    end
  end

  devise_for :users, path:"account", controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :notifications do
    collection do
      post :clean
    end
  end

  resources :comments, only: [:destroy]
  resources :statuses, only: [:index, :show, :destroy] do
    resources :comments, only: [:new, :create]
  end

  ##
  # 管理
  authenticate :user, -> (user) { user.admin? } do
    scope :admin do
      resources :statistics, only: [:index]
      mount PgHero::Engine, at: "pghero"
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 会匹配所有剩下的 url，并 render error，它之后的 route 不会匹配
  # match '*path', to: 'home#error_404', via: :all

end

app/views/shared/_captcha.html.erb
<div class="form-group rucaptcha">
  <%= rucaptcha_input_tag(placeholder: t('rucaptcha.input'), size: 20, type: "text", class: "form-control") %>
  <a class="rucaptcha-image-box" href="#"><%= rucaptcha_image_tag %></a>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="alert alert-block alert-danger">
    <a class="close" data-dismiss='alert' href="#">×</a>
    <p><strong>有 <%= target.errors.count %> 处问题导致无法提交:</strong></p>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login.html.erb
<div class="sign-in card border-none">
  <%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
    <%= f.input :email, label: false, placeholder: "请输入邮箱" %>
    <%= f.input :password, label: false, placeholder: "请输入密码" %>
    <%= render "shared/captcha" %>
    <div>
      <%= f.input :remember_me, as: :boolean, label: "勿忘我" %>
    </div>
    <%= f.button :submit, t('devise.shared.links.sign_in'), class: "btn btn-success" %>
    <%= link_to "注 册", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to t("devise.shared.links.forgot_your_password"), new_password_path(:user) %>
  <% end %>
</div>

app/views/shared/_users_list.html.erb
<ul class="unstyled user-list">
  <% users.each do |user| %>
  	<% if user %>
	    <li>
	       <%= link_to image_tag(user.avatar.tiny.url.to_s, class: "avatar tiny"), user, title: user.name, data: {toggle: 'tooltip'}, target: '_blank' %>
	    </li>
    <% end %>
  <% end %>
</ul>