config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: "home#index", as: :user_root

  resources :relations, only: [:create, :destroy] do
    collection do
      get "refresh"
      post "refresh_list"
    end
  end

  get "@:id" => "users#show", as: :user

  resources :projects, path: :diy

  resources :publications, only: [:create, :destroy] do
    new do
      get ':type', action: :new, as: ""
    end
    collection do
      post "trix_attachment"
    end
    member do
      get '(/:index)', action: :show, as: ""
    end
  end

  devise_for :users, path:"account", controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :notifications do
    collection do
      post :clean
    end
  end

  resources :comments, only: [:destroy]
  resources :statuses, only: [:index, :show, :destroy] do
    resources :comments, only: [:new, :create]
  end

  ##
  # 管理
  authenticate :user, -> (user) { user.admin? } do
    scope :admin do
      resources :statistics, only: [:index]
      mount PgHero::Engine, at: "pghero"
    end
  end
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # 会匹配所有剩下的 url，并 render error，它之后的 route 不会匹配
  # match '*path', to: 'home#error_404', via: :all

end

app/models/project.rb
class Project < ApplicationRecord
  # 项目也有很多事件，比如创建。当项目不在时，也还是算用户的，需要在其也没显示，只是项目名标识一下
  include Statusable
  include Relationable

  extend FriendlyId
  friendly_id :name

  # 在 project show 里每页显示的 status 的个数
  STATUSES_PER_PAGE = 18

  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  # 用来查找 project 所有的 statuses
  has_many :all_statuses, class_name: :Status

  has_many :publications

  # before validates
  auto_strip_attributes :name, :desc,
                        delete_whitespaces: true, nullify: false
  auto_strip_attributes :description,
                        squish: true, nullify: false

  validates :name, presence: true, length: 2..20, uniqueness: { case_sensitive: false }
  validates :desc, presence: true, length: 2..50
  validates :description, length: 0..10000
  validates :avatar, file_size: { less_than: 10.megabytes.to_i }

  after_create :create_tmp_profile

  def create_tmp_profile
    if avatar.blank?
      File.open(LetterAvatar.generate(PinYin.abbr(name), 180)) do |f|
        self.avatar = f
      end
      save
    end
  end

  def status_action_type
    "project"
  end

  def content_type
    "project"
  end

  def project
    self
  end

  # Project 里只需要出现有用的东西，
  # 即 pubications 的发布，项目的创建，有人 follow 项目（好来欢迎）
  def statuses_to_show
    all_statuses.where(
      action_type: %w(publication follow project) )
  end

  # 返回一个 status 在 project show 里的 page 页数
  # TODO 如果没有 project 呢？
  def page_of_status(status)
    before_count = statuses_to_show.where("id > ?", status.id).count
    before_count / STATUSES_PER_PAGE + 1
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    authorize Project
    @projects = Project.all.paginate(page: params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @statuses = @project.statuses_to_show.paginate(page: params[:page], per_page: Project::STATUSES_PER_PAGE)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    authorize @project
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'DIY 创建成功！' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'DIY 更新成功。' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  # TODO soft delete
  def destroy
    # @project.destroy
    # respond_to do |format|
    #   format.html { redirect_to projects_url, notice: 'DIY 删除成功。' }
    #   format.json { head :no_content }
    # end
    redirect_to '/'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
      authorize @project
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :avatar, :desc, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, validate: true, html: { multipart: true } do |f| %>
  <%= render "shared/error_messages", target: @project %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= avatar_tag(@project, :normal, link: false) if @project.avatar.present? %>
    <%= f.input :avatar %>
    <%= f.trix_editor :description, :input_html => {rows: 10} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_projects_list_big.html.erb
<div class="projects-list">
  <ul class="media-list">
    <% projects.each do |project| %>
      <% cache project do %>
        <li class="media">
          <div class="media-top">
            <%= avatar_tag project, :big %>
          </div>
          <div class="media-body">
            <div class="name">
              <%= project.name %>
            </div>
            <div class="desc">
              <%= project.desc %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/projects/_projects_list_small.html.erb
<% if projects %>
  <ul class="unstyled projects-list-small media-list">
    <% projects.each do |project| %>
      <% cache project do %>
        <li class="media mover">
          <div class="media-left mr-2">
            <%= avatar_tag(project, :small) %>
          </div>
          <div class="media-body">
            <div class="media-heading">
              <%= link_to project.name, project_path(project) %>
            </div>
            <div class="media-content text-muted">
              <%= project.desc %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/projects/change_reply_type.js.erb
$("#publishable_type").val('<%= @type %>')
$("#input-content").html("<%=j render('projects/replies/' + @type) %>")

app/views/projects/edit.html.erb
<h1>编辑 DIY</h1>

<%= render 'form', project: @project %>

<%= link_to '返回', @project %>

<% content_for "secondary-content" do %>
  来和大家分享吧！
<% end %>

app/views/projects/index.html.erb
<% cache @projects do %>
  <%= render "projects_list_big", projects: @projects %>
  <%= will_paginate @projects %>
<% end %>

app/views/projects/new.html.erb
<h1>创建 DIY</h1>

<%= render 'form', project: @project %>

<% content_for "secondary-content" do %>
  来和大家分享吧！
<% end %>

app/views/projects/show.html.erb
<%= render "shared/error_messages", target: @project %>

<div class="project-description">
  <h1 class=""><%= @project.name %></h1>
  <h6 class="text-muted"><%= @project.desc %></h6>
  <hr />
  <div class="trix-content">
    <%= sanitize @project.description %>
  </div>
</div>

<hr />

<%= render partial: "statuses/status", collection: @statuses %>
<%= render "publications/new/form", project: @project if current_user == @project.user%>
<%= will_paginate @statuses %>

<% content_for "secondary-content" do %>
  <div class="section">
    <div class="border-none card text-center ">
      <div class="card-image-top">
        <%= avatar_tag @project, :big, link: false %>
      </div>
      <div class="card-block">
        <div class="btn-group" role="group">
          <%= render "relations/follow_project", relationable: @project %>
        </div>

        <% if policy(@project).edit? %>
          <%= link_to "编辑", edit_project_path(@project),
            class: "btn btn-secondary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="section">
    <h2>作者</h2>
    <%= render "users/user_item_small", user: @project.user %>
  </div>

  <div class="section">
    <h2>最近关注</h2>
    <%= render "users/users_list_tiny", users: @project.who_follow %>
  </div>

<% end %>